apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: random-ingress
  namespace: random-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #Configurations are available here:
    #https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
    #https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/
    # nginx.ingress.kubernetes.io/worker-shutdown-timeout: 3600000s
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "36000000"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "36000000"
    # nginx.ingress.kubernetes.io/proxy-stream-timeout: "36000000"
    # nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "36000000"
    # nginx.org/websocket-services: random-service
    # kubernetes.io/ingress.class: nginx
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - host: random.demo
    http:
      paths:
      - path: /
        backend:
          serviceName: random-service
          servicePort: 80
      - path: /socket.io
        backend:
          serviceName: random-service
          servicePort: 80
